testing compound messaging in workflow log

diff --git a/.github/workflows/jira_automation.yaml b/.github/workflows/jira_automation.yaml
--- a/.github/workflows/jira_automation.yaml
+++ b/.github/workflows/jira_automation.yaml
@@ -47,34 +47,36 @@ jobs:
       - name: Install Dependencies
 #        if: steps.week_check.outputs.proceed == 'true'
         run: |
-          echo "Initializing dependency installation.."
-          set -e
-
-          python -m pip install --upgrade pip --quiet 2> pip_upgrade_error.log || echo $? > exit_code.txt
-          pip install --quiet certifi hypothesis requests pydantic pyyaml 2> pip_install_error.log || echo $? >> exit_code.txt
-
-          # Did a step fail?
-          if [ -s exit_code.txt ]; then
-            echo -e "\033[0;31mDependency installation failed.\033[0m"
+          bash -c '
             echo
+            echo "Initializing dependency installation.."
+          
+            set -e
+            python -m pip install --upgrade pip --quiet 2> pip_upgrade_error.log || echo $? > exit_code.txt
+            pip install --quiet certifi hypothesis requests pydantic pyyaml 2> pip_install_error.log || echo $? >> exit_code.txt
 
-            if [ -s pip_upgrade_error.log ]; then
-              echo -e "\033[0;33m--- pip upgrade error log ---\033[0m"
-              cat pip_upgrade_error.log
+            if [ -s exit_code.txt ]; then
+              echo -e "\033[0;31mDependency installation failed.\033[0m"
               echo
-            fi
 
-            if [ -s pip_install_error.log ]; then
-              echo -e "\033[0;33m--- pip install error log ---\033[0m"
-              cat pip_install_error.log
+              if [ -s pip_upgrade_error.log ]; then
+                echo -e "\033[0;33m--- pip upgrade error log ---\033[0m"
+                cat pip_upgrade_error.log
+                echo
+              fi
+
+              if [ -s pip_install_error.log ]; then
+                echo -e "\033[0;33m--- pip install error log ---\033[0m"
+                cat pip_install_error.log
+                echo
+              fi
+
+              exit 1
+            else
               echo
+              echo -e "\033[0;32mDependency installation successful.\033[0m"
             fi
-
-            exit 1
-          else
-            echo
-            echo -e "\033[0;32mDependency installation successful.\033[0m"
-          fi
+          '
 
 
         # Run the script with stored secrets
